# Generated by Django 3.1.4 on 2021-01-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exfd',
            name='impf',
            field=models.ImageField(default='mobile.jpg', upload_to='logo/'),
        ),
    ]
