# Generated by Django 3.1.4 on 2021-01-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjProject', '0002_auto_20210103_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exfd',
            name='impf',
            field=models.ImageField(default='mobile.jpg', upload_to='Profile/'),
        ),
    ]
